id = "ubuntu-yaru-theme"
name = "Ubuntu Yaru Theme"
schema_version = 1
version = "0.0.1"
authors = ["deadmau5v <deadmau5v@qq.com>"]
description = "Ubuntu Yaru Theme for Zed"
repository = "https://github.com/deadmau5v/ubuntu-yaru-theme"
